ALTER TABLE users DROP PRIMARY KEY;
ALTER TABLE users MODIFY id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY;

ALTER TABLE employees DROP PRIMARY KEY;
ALTER TABLE employees MODIFY id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY;

ALTER TABLE user_role DROP PRIMARY KEY;
ALTER TABLE user_role MODIFY id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY;
