ALTER TABLE users MODIFY id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT;
ALTER TABLE employees MODIFY id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT;
ALTER TABLE user_role MODIFY id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT;
